version: '3.8' 
services:
  model:
    build: 
      context: model/
    container_name: model
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  
    environment:
      - CUDA_VISIBLE_DEVICES=all
    volumes:
      - .:/app  
    runtime: nvidia  

